USE [master]
GO

/****** Object:  Database [ConsultingRoom]    Script Date: 4.7.2022 г. 21:49:56 ******/
CREATE DATABASE [ConsultingRoom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ConsultingRoom', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ConsultingRoom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ConsultingRoom_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ConsultingRoom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConsultingRoom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConsultingRoom] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ConsultingRoom] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ConsultingRoom] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ConsultingRoom] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ConsultingRoom] SET ARITHABORT OFF 
GO

ALTER DATABASE [ConsultingRoom] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ConsultingRoom] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ConsultingRoom] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ConsultingRoom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ConsultingRoom] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ConsultingRoom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ConsultingRoom] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ConsultingRoom] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ConsultingRoom] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ConsultingRoom] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ConsultingRoom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ConsultingRoom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ConsultingRoom] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ConsultingRoom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ConsultingRoom] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ConsultingRoom] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ConsultingRoom] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ConsultingRoom] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ConsultingRoom] SET  MULTI_USER 
GO

ALTER DATABASE [ConsultingRoom] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ConsultingRoom] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ConsultingRoom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ConsultingRoom] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ConsultingRoom] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ConsultingRoom] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ConsultingRoom] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ConsultingRoom] SET  READ_WRITE 
GO

